### PR TITLE
Update InputSettings.cs

### PR DESCRIPTION
**Pull request by celestial-labs**
remove unused import.

Now its working in Unity 2019.3.

Before I got this exception:
`Library\PackageCache\com.unity.inputsystem@0.2.8-preview\InputSystem\InputSettings.cs(5,32): error CS0234: The type or namespace name 'PlayerLoop' does not exist in the namespace 'UnityEngine.Experimental' (are you missing an assembly reference?)`

### CODE REVIEW

**Comment by jechter** [comment]
Thanks @alexSanni ! However, this fix already landed in https://github.com/Unity-Technologies/InputSystem/commit/8692c2ade36b4e615a5ed89a59cb65fc062f4e27
