### ISSUE TITLE
0.0.12-preview does not compile in 2018.2.16 due to NUnit reference

### ISSUE THREAD

**Issue by CarpetHead** [Unity-Technologies/InputSystem#308]
seems to be easy to reproduce, let me know if more info is required. Try in an empty project

**Comment by Wokarol** [comment]
Do you have package added in manifest file?

**Comment by CarpetHead** [comment]
Yep, this is when I updated from 0.0.10-preview to 0.0.12-preview. I get the error 

`The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: Packages\com.unity.inputsystem\InputSystem\Editor\InputActionAsset\InputTreeViewLine.cs(5,7)`

Deleting the using line fixes the issue

**Comment by KospY** [comment]
Also got the same issue.

**Comment by Wokarol** [comment]
I just got the issue yesterday, but restart of pc worked

**Comment by Wokarol** [comment]
New info:
I get that error every time I change any script name, restarting Unity "solves" this problem

**Comment by Rene-Damm** [comment]
Sorry about that. Not quite sure how that made it through. We still don't have QA in place for when we publish (will happen soon) which is why we're still on staging only, but the compile problem should have been caught by the farm.

Compile error fixed in https://github.com/Unity-Technologies/InputSystem/commit/acda8385f5f8241f4bffa6c08c4992f2f64bba85.

**Comment by Rene-Damm** [comment]
Should be fixed in 0.0.13-preview.
