### ISSUE TITLE
The new InputSystem preview doesn't work in the Linux Editor (Unity-2018.2.0f2)

### ISSUE THREAD

**Issue by michael-nischt** [Unity-Technologies/InputSystem#181]
The new InputSystem preview doesn't work in the Linux Editor (Unity-2018.2.0f2). Running the Demo scene and launching the Input Debug window list 0 devices despite having a Dualshock 4 and a Steam Controller connected in addition to mouse and keyboard.

**Comment by Rene-Damm** [comment]
Ah yup, unfortunately we don't have Linux support in 2018.2. It's coming in 2018.3 and should be available during the beta phase.

**Comment by Rene-Damm** [comment]
To add some more detail, Linux, WebGL, and UWP (got basic mouse and keyboard support but nothing else) were the three platforms that didn't make the 2018.2 deadline. All three are targeted for 2018.3.

**Comment by michael-nischt** [comment]
Thanks for the quick reply. 
FYI: I think mouse support isn't working either atm. I added the left mouse button to the `fire action` but it had no effect.

**Comment by Rene-Damm** [comment]
Sorry, wasn't very specific there. Only UWP has basic mouse and keyboard support in 2018.2. Linux and WebGL have no backends entirely. A 2018.3 beta with initial backends for those platforms should be available pretty soon.

**Comment by Rene-Damm** [comment]
Should be out and functional in 2018.3.

**Comment by michael-nischt** [comment]
Cool!
I cloned the repository again and there are no compilation errors nor exceptions. However, the demo scene seems not to register any input (tested with mouse+kb and a Steam Controller). Player settings enabled both input systems. Anything else I need to do?

(Unity-2018.3.1f1)

P.S. there is one warning: 
Package missing for Virtual Reality SDK Oculus. Please add the Oculus (Standalone) package using the Package Manager Window. Will attempt to enable None instead.

**Comment by Rene-Damm** [comment]
The demo is non-functional ATM as a new demo is being built there. The old demo is in SimpleDemo. Probably wouldn't have been better to leave the old demo in place until the new one is finished. Sorry for the confusion.
